# Add to ~/.config/kitty/kitty.conf
background #1d2230
foreground #e3e5e5
cursor #a3aed2
cursor_text_color #1d2230
selection_background #394260
selection_foreground #e3e5e5
color4 #769ff0
color12 #a3aed2
